on:
  push:
    branches:
      - master

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build-amd64
      - uses: actions/upload-artifact@v4
        with:
          name: layers-amd64
          path: layers/

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - run: make build-arm64
      - uses: actions/upload-artifact@v4
        with:
          name: layers-arm64
          path: layers/
